import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) 
{
  return (
    <html lang="en" >
      <body className={`h-full bg-gradient-to-r from-indigo-500 via-violet-900 to-purple-600 font-sans ${inter.variable}`}>
        <TRPCReactProvider>{children}</TRPCReactProvider>

      <footer className="bg-black opacity-40 h-20 text-white inset-x-0 bottom-0 text-center">© Reactaurant, Inc.
</footer>
      </body>

    </html>
  );
}
